theme: jekyll-theme-cayman
defaults:
  - scope:
      path: ""
    values:
      title: "⚙️ Morten Andersen ⚙️ Tech Notes & Mindmaps"
      image:
        path: /assets/tech.jpg
        height: 640
        width: 1280
